---
- name: Include OS based tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-ansible_distribution_major_version }}/main.yaml"
    - "{{ ansible_distribution | lower }}/main.yaml"
