---
certs_and_config_kube_api_public_ip: "192.168.1.100"
certs_and_config_cluster_name: "rpi-cluster"
certs_and_config_encryption_secret: "{{ lookup('env', 'ANSIBLE_K8S_ENCRYPTION_SECRET') | default(lookup('password', '../config/encryption_key chars=ascii_letters,digits length=32'), true) }}"
certs_and_config_kube_api_additional_subject_alt_names_list:
  - kubernetes.default
  - kubernetes.default.svc
  - kubernetes.default.svc.cluster
  - kubernetes.svc.cluster.local
