apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: gitea-shared-db
spec:
  name: gitea
  host: '%'
  passwordSecretKeyRef:
    key: password
    name: gitea-db-user
  mariaDbRef:
    name: shared-mariadb
    namespace: database
