apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: nextcloud-shared-db
spec:
  name: nextcloud
  host: '%'
  maxUserConnections: 100
  passwordSecretKeyRef:
    key: password
    name: mariadb-nextcloud
  mariaDbRef:
    name: shared-mariadb
    namespace: database
