controller:
  electionID: external-ingress-controller
  ingressClassResource:
    name: external-nginx  # default: nginx
    enabled: true
    default: false
    controllerValue: "k8s.io/external-ingress-nginx"  # default: k8s.io/ingress-nginx
  service:
    annotations:
      metallb.universe.tf/address-pool: external
      metallb.universe.tf/allow-shared-ip: external
  config:
    enable-real-ip: "true"
    use-forwarded-headers: "true"
    forwarded-for-header: "CF-Connecting-IP"
    proxy-real-ip-cidr: "172.16.0.0/12"
