apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: nextcloud
spec:
  mariaDbRef:
    name: shared-mariadb
    namespace: database
  characterSet: utf8mb4
  collate: utf8mb4_general_ci
