# Manually managed kubernetes objects goes here, just to keep things clean
- hosts: localhost
  any_errors_fatal: true
  become: false
  tasks:
    - name: Create a service for external Emby media server
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: emby
            namespace: media
            labels:
              app: emby
          spec:
            type: LoadBalancer
            ports:
              - protocol: TCP
                port: 8096
                targetPort: 9096
      tags: emby

    - name: Create endpoint for Emby service
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          apiVersion: v1
          kind: Endpoints
          metadata:
            name: emby
            namespace: media
            labels:
              app: emby
          subsets:
            - addresses:
              - ip: 192.168.1.129
              ports:
                - port: 9096
                  protocol: "TCP"
      tags: emby

    - name: Create ingress for Emby
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          apiVersion: v1
          kind: Ingress
          metadata:
            name: emby
            namespace: media
            labels:
              app: emby
            annotations:
              external-dns.alpha.kubernetes.io/hostname: emby.pco.pink
              cert-manager.io/cluster-issuer: letsencrypt
              nginx.ingress.kubernetes.io/configuration-snippet: |
                proxy_set_header Range $http_range;
                proxy_set_header If-Range $http_if_range;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                gzip on;
                gzip_disable "msie6";
                gzip_comp_level 6;
                gzip_min_length 1100;
                gzip_buffers 16 8k;
                gzip_proxied any;
                gzip_types
                  text/plain
                  text/css
                  text/js
                  text/xml
                  text/javascript
                  application/javascript
                  application/x-javascript
                  application/json
                  application/xml
                  application/rss+xml
                  image/svg+xml;
                tcp_nodelay on;
          spec:
            rules:
              - host: emby.pco.pink
                http:
                  paths:
                    - backend:
                        service:
                          name: emby
                          port:
                            number: 8096
                      path: /
                      pathType: Prefix
            tls:
              - hosts:
                - emby.pco.pink
                secretName: emby-tls-cert
      tags: emby

    - name: Create a service for nzbget on TrueNAS
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: nzbget
            namespace: media
            labels:
              app: nzbget
          spec:
            ports:
              - protocol: TCP
                port: 10057
                targetPort: 10057
      tags: nzbget

    - name: Create endpoint for nzbget service
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          apiVersion: v1
          kind: Endpoints
          metadata:
            name: nzbget
            namespace: media
            labels:
              app: nzbget
          subsets:
            - addresses:
              - ip: 192.168.1.129
              ports:
                - port: 10057
                  protocol: TCP
      tags: nzbget

    - name: Create ingress for nzbget
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          apiVersion: v1
          kind: Ingress
          metadata:
            name: nzbget
            namespace: media
            labels:
              app: nzbget
            annotations:
              external-dns.alpha.kubernetes.io/hostname: nzbget.pco.pink
              cert-manager.io/cluster-issuer: letsencrypt
          spec:
            rules:
              - host: nzbget.pco.pink
                http:
                  paths:
                    - backend:
                        service:
                          name: nzbget
                          port:
                            number: 10057
                      path: /
                      pathType: Prefix
            tls:
              - hosts:
                - nzbget.pco.pink
                secretName: nzbget-tls-cert
      tags: nzbget

    - name: Create a service for qbit on TrueNAS
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: qbit
            namespace: media
            labels:
              app: qbit
          spec:
            ports:
              - protocol: TCP
                port: 10095
                targetPort: 10095
      tags: qbit

    - name: Create endpoint for qbit service
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          apiVersion: v1
          kind: Endpoints
          metadata:
            name: qbit
            namespace: media
            labels:
              app: qbit
          subsets:
            - addresses:
              - ip: 192.168.1.129
              ports:
                - port: 10095
                  protocol: TCP
      tags: qbit

    - name: Create ingress for qbit
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          apiVersion: v1
          kind: Ingress
          metadata:
            name: qbit
            namespace: media
            labels:
              app: qbit
            annotations:
              external-dns.alpha.kubernetes.io/hostname: qbit.pco.pink
              cert-manager.io/cluster-issuer: letsencrypt
          spec:
            rules:
              - host: qbit.pco.pink
                http:
                  paths:
                    - backend:
                        service:
                          name: qbit
                          port:
                            number: 10095
                      path: /
                      pathType: Prefix
            tls:
              - hosts:
                - qbit.pco.pink
                secretName: qbit-tls-cert
      tags: qbit

    - name: Create ingress for V Rising server
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          kind: Service
          apiVersion: v1
          metadata:
            name: vrising-server
            namespace: default
            labels:
              app: vrising-server
            annotations:
              external-dns.alpha.kubernetes.io/hostname: vrising.pco.pink
          spec:
            type: ExternalName
            externalName: 212.149.199.26
      tags: vrising

    - name: Create internal ip pool for metallb
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          kind: IPAddressPool
          apiVersion: metallb.io/v1beta1
          metadata:
            name: internal
            namespace: metallb-system
          spec:
            addresses:
              - 192.168.50.0-192.168.50.254
      tags: metallb

    - name: Create external ip pool for metallb
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          kind: IPAddressPool
          apiVersion: metallb.io/v1beta1
          metadata:
            name: external
            namespace: metallb-system
          spec:
            addresses:
              - 192.168.50.255/32
            autoAssign: false
      tags: metallb

    - name: Create L2 advertisement for metallb
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          kind: L2Advertisement
          apiVersion: metallb.io/v1beta1
          metadata:
            name: home-net
            namespace: metallb-system
      tags: metallb
