# Manually managed kubernetes objects goes here, just to keep things clean
- hosts: localhost
  connection: local
  any_errors_fatal: true
  become: false
  tasks:
    - name: Create a service for external Emby media server
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: emby
            namespace: media
            labels:
              app: emby
          spec:
            type: LoadBalancer
            ports:
              - protocol: TCP
                port: 8096
                targetPort: 9096
      tags: emby

    - name: Create endpoint for Emby service
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          apiVersion: v1
          kind: Endpoints
          metadata:
            name: emby
            namespace: media
            labels:
              app: emby
          subsets:
            - addresses:
              - ip: 192.168.1.129
              ports:
                - port: 9096
                  protocol: "TCP"
      tags: emby

    - name: Create ingress for Emby
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          apiVersion: v1
          kind: Ingress
          metadata:
            name: emby
            namespace: media
            labels:
              app: emby
            annotations:
              external-dns.alpha.kubernetes.io/hostname: emby.pco.pink
              cert-manager.io/cluster-issuer: letsencrypt
              nginx.ingress.kubernetes.io/configuration-snippet: |
                proxy_set_header Range $http_range;
                proxy_set_header If-Range $http_if_range;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                gzip on;
                gzip_disable "msie6";
                gzip_comp_level 6;
                gzip_min_length 1100;
                gzip_buffers 16 8k;
                gzip_proxied any;
                gzip_types
                  text/plain
                  text/css
                  text/js
                  text/xml
                  text/javascript
                  application/javascript
                  application/x-javascript
                  application/json
                  application/xml
                  application/rss+xml
                  image/svg+xml;
                tcp_nodelay on;
          spec:
            rules:
              - host: emby.pco.pink
                http:
                  paths:
                    - backend:
                        service:
                          name: emby
                          port:
                            number: 8096
                      path: /
                      pathType: Prefix
            tls:
              - hosts:
                - emby.pco.pink
                secretName: emby-tls-cert
      tags: emby

    - name: Create a service for nzbget on TrueNAS
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: nzbget
            namespace: media
            labels:
              app: nzbget
          spec:
            ports:
              - protocol: TCP
                port: 10057
                targetPort: 10057
      tags: nzbget

    - name: Create endpoint for nzbget service
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          apiVersion: v1
          kind: Endpoints
          metadata:
            name: nzbget
            namespace: media
            labels:
              app: nzbget
          subsets:
            - addresses:
              - ip: 192.168.1.129
              ports:
                - port: 10057
                  protocol: TCP
      tags: nzbget

    - name: Create ingress for nzbget
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          apiVersion: v1
          kind: Ingress
          metadata:
            name: nzbget
            namespace: media
            labels:
              app: nzbget
            annotations:
              external-dns.alpha.kubernetes.io/hostname: nzbget.pco.pink
              cert-manager.io/cluster-issuer: letsencrypt
              nginx.ingress.kubernetes.io/proxy-body-size: "0"
              nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
              nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
          spec:
            rules:
              - host: nzbget.pco.pink
                http:
                  paths:
                    - backend:
                        service:
                          name: nzbget
                          port:
                            number: 10057
                      path: /
                      pathType: Prefix
            tls:
              - hosts:
                - nzbget.pco.pink
                secretName: nzbget-tls-cert
      tags: nzbget

    - name: Create a service for qbit on TrueNAS
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: qbit
            namespace: media
            labels:
              app: qbit
          spec:
            ports:
              - protocol: TCP
                port: 10095
                targetPort: 10095
      tags: qbit

    - name: Create endpoint for qbit service
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          apiVersion: v1
          kind: Endpoints
          metadata:
            name: qbit
            namespace: media
            labels:
              app: qbit
          subsets:
            - addresses:
              - ip: 192.168.1.129
              ports:
                - port: 10095
                  protocol: TCP
      tags: qbit

    - name: Create ingress for qbit
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          apiVersion: v1
          kind: Ingress
          metadata:
            name: qbit
            namespace: media
            labels:
              app: qbit
            annotations:
              external-dns.alpha.kubernetes.io/hostname: qbit.pco.pink
              cert-manager.io/cluster-issuer: letsencrypt
          spec:
            rules:
              - host: qbit.pco.pink
                http:
                  paths:
                    - backend:
                        service:
                          name: qbit
                          port:
                            number: 10095
                      path: /
                      pathType: Prefix
            tls:
              - hosts:
                - qbit.pco.pink
                secretName: qbit-tls-cert
      tags: qbit

    - name: Create internal ip pool for metallb
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          kind: IPAddressPool
          apiVersion: metallb.io/v1beta1
          metadata:
            name: internal
            namespace: metallb-system
          spec:
            addresses:
              - 192.168.50.0-192.168.50.254
      tags: metallb

    - name: Create external ip pool for metallb
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          kind: IPAddressPool
          apiVersion: metallb.io/v1beta1
          metadata:
            name: external
            namespace: metallb-system
          spec:
            addresses:
              - 192.168.50.255/32
            autoAssign: false
      tags: metallb

    - name: Create L2 advertisement for metallb
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          kind: L2Advertisement
          apiVersion: metallb.io/v1beta1
          metadata:
            name: home-net
            namespace: metallb-system
      tags: metallb

    - name: Create a service for bazarr on TrueNAS
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: bazarr
            namespace: media
            labels:
              app: bazarr
          spec:
            ports:
              - protocol: TCP
                port: 6767
                targetPort: 6767
      tags: bazarr

    - name: Create endpoint for bazarr service
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          apiVersion: v1
          kind: Endpoints
          metadata:
            name: bazarr
            namespace: media
            labels:
              app: bazarr
          subsets:
            - addresses:
              - ip: 192.168.1.129
              ports:
                - port: 6767
                  protocol: TCP
      tags: bazarr

    - name: Create ingress for bazarr
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          apiVersion: v1
          kind: Ingress
          metadata:
            name: bazarr
            namespace: media
            labels:
              app: bazarr
            annotations:
              external-dns.alpha.kubernetes.io/hostname: bazarr.pco.pink
              cert-manager.io/cluster-issuer: letsencrypt
          spec:
            rules:
              - host: bazarr.pco.pink
                http:
                  paths:
                    - backend:
                        service:
                          name: bazarr
                          port:
                            number: 6767
                      path: /
                      pathType: Prefix
            tls:
              - hosts:
                - bazarr.pco.pink
                secretName: bazarr-tls-cert
      tags: bazarr

    - name: Create namespace for Github self-hosted runners
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: github-runners

    - name: Create Github RunnerDeployment for mysql-operator
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          apiVersion: actions.summerwind.dev/v1alpha1
          kind: RunnerDeployment
          metadata:
            name: mysql-operator-runners
            namespace: github-runners
          spec:
            template:
              spec:
                dockerMTU: 1450 # thanks to flannel this is 1450 on hosts and can't be changed
                                # this created so much trouble... failed TLS handshakes were all over the place
                                # should stay here if you use DinD to build your images.
                repository: canozokur/mysql-operator

    - name: Create Github HPA for mysql-operator-runners
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          apiVersion: actions.summerwind.dev/v1alpha1
          kind: HorizontalRunnerAutoscaler
          metadata:
            name: mysql-operator-runners
            namespace: github-runners
          spec:
            minReplicas: 0
            maxReplicas: 10
            scaleTargetRef:
              kind: RunnerDeployment
              name: mysql-operator-runners
            scaleUpTriggers:
              - githubEvent:
                  workflowJob: {}
                duration: "30m"

    - name: Create Github RunnerDeployment for mysql-docker
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          apiVersion: actions.summerwind.dev/v1alpha1
          kind: RunnerDeployment
          metadata:
            name: mysql-docker-runners
            namespace: github-runners
          spec:
            template:
              spec:
                dockerMTU: 1450 # thanks to flannel this is 1450 on hosts and can't be changed
                                # this created so much trouble... failed TLS handshakes were all over the place
                                # should stay here if you use DinD to build your images.
                repository: canozokur/mysql-docker

    - name: Create Github HPA for mysql-docker-runners
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          apiVersion: actions.summerwind.dev/v1alpha1
          kind: HorizontalRunnerAutoscaler
          metadata:
            name: mysql-docker-runners
            namespace: github-runners
          spec:
            minReplicas: 0
            maxReplicas: 10
            scaleTargetRef:
              kind: RunnerDeployment
              name: mysql-docker-runners
            scaleUpTriggers:
              - githubEvent:
                  workflowJob: {}
                duration: "30m"
