---
- hosts: all
  gather_facts: true
  any_errors_fatal: true
  become: true
  become_method: community.general.sudosu
  handlers:
    - name: restart journald
      service:
        name: systemd-journald
        state: restarted
    
    - name: restart multipathd
      service:
        name: multipathd
        state: restarted

  roles:
    - role: configure_ssh
    - role: install_yay

  tasks:
    - name: Install misc. packages
      package:
        name: "{{ item }}"
        state: present
      loop:
        - htop
        - lm_sensors
        - vim
        - bash-completion
        - xfsprogs
        - cpupower # to set cpu freq scaling
        - nfs-utils # for TrueNAS CSI
        - open-iscsi # for TrueNAS CSI
        - multipath-tools # for TrueNAS CSI iscsi

    - name: Ensure journald config directory exists
      file:
        dest: /etc/systemd/journald.conf.d
        owner: root
        group: root
        mode: '0755'
        state: directory

    - name: Configure journald for volatile storage
      copy:
        dest: /etc/systemd/journald.conf.d/99-user-settings.conf
        content: |
          [Journal]
          Storage=volatile
          Compress=yes
          SystemMaxUse=100M
          RuntimeMaxUse=100M
        owner: root
        group: root
        mode: '0644'
      notify: restart journald
    
    - name: Enable and start cpupower daemon
      service:
        name: cpupower
        state: started
        enabled: true

    - name: Set the cpu scaling governor to performance
      command: cpupower frequency-set -g performance

    - name: Configure multipathd for TrueNAS
      copy:
        dest: /etc/multipath.conf
        content: |
          defaults {
            user_friendly_names yes
            find_multipaths yes
          }
        owner: root
        group: root
        mode: '0644'
      notify: restart multipathd
  
    - name: Enable iscsi services
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - multipathd
        - iscsid
