---
- hosts: all
  gather_facts: true
  any_errors_fatal: true
  become: true
  tasks:
    - name: Install open-iscsi
      ansible.builtin.package:
        name: open-iscsi
        state: present
    
    - name: Enable and start iscsid
      ansible.builtin.service:
        name: iscsid
        state: started
        enabled: true
    
    - name: Install nfs
      ansible.builtin.package:
        name: nfs-utils
        state: present

- hosts: localhost
  gather_facts: false
  any_errors_fatal: true
  become: false
  tasks:
    - name: Create a new k8s namespace for longhorn
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: longhorn-system
            labels:
              app: longhorn

    - name: Add MetalLB helm repo
      kubernetes.core.helm_repository:
        name: longhorn
        repo_url: https://charts.longhorn.io

    - name: Deploy longhorn
      kubernetes.core.helm:
        name: longhorn
        chart_ref: longhorn/longhorn
        kubeconfig: ../config/admin.kubeconfig
        release_namespace: longhorn-system
        values: "{{ lookup('template', 'longhorn/values.yaml') | from_yaml }}"
