---
- hosts: all
  gather_facts: true

- hosts: localhost
  any_errors_fatal: true
  roles:
    - role: certs_and_config
      vars:
        certs_and_config_kube_api_public_ip: 192.168.10.1
        certs_and_config_cluster_name: rpi-cluster

- hosts: etcd
  any_errors_fatal: true
  become: true
  roles:
    - role: etcd_cluster
      vars:
        etcd_cluster_log_level: warn

- hosts: all
  any_errors_fatal: true
  become: true
  roles:
    - role: provision_control_plane
      vars:
        provision_control_plane_kube_api_public_ip: 192.168.10.1
        provision_control_plane_service_ip_range: 192.168.10.0/24
        provision_control_plane_pod_ip_range: 172.28.0.0/16
        provision_control_plane_verbose_logs: false
    - role: configure_ha
      vars:
        configure_ha_kube_api_public_ip: 192.168.10.1

- hosts: localhost
  any_errors_fatal: true
  tasks:
    - name: Create cluster role for kubelet auth
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRole
          metadata:
            annotations:
              rbac.authorization.kubernetes.io/autoupdate: "true"
            labels:
              kubernetes.io/bootstrapping: rbac-defaults
            name: system:kube-apiserver-to-kubelet
          rules:
            - apiGroups:
                - ""
              resources:
                - nodes/proxy
                - nodes/stats
                - nodes/log
                - nodes/spec
                - nodes/metrics
              verbs:
                - "*"

    - name: Create cluster role binding for kubelet auth
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: system:kube-apiserver
            namespace: ""
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: system:kube-apiserver-to-kubelet
          subjects:
            - apiGroup: rbac.authorization.k8s.io
              kind: User
              name: kubernetes

- hosts: all
  any_errors_fatal: true
  become: true
  roles:
    - role: provision_nodes
      vars:
        provision_nodes_pod_ip_range: 172.28.0.0/16
      tags:
        - nodes

# Manually managed kubernetes objects goes here, just to keep things clean
- hosts: localhost
  any_errors_fatal: true
  become: false
  vars:
    metallb_loadbalancer_range: 192.168.50.0/24
  tasks:
    - name: Create a new k8s namespace for metallb
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: metallb-system
            labels:
              app: metallb
      tags: metallb

    - name: Add MetalLB helm repo
      kubernetes.core.helm_repository:
        name: metallb
        repo_url: https://metallb.github.io/metallb
      tags: metallb

    - name: Deploy MetalLB version 0.12.1
      kubernetes.core.helm:
        name: metallb
        chart_ref: metallb/metallb
        kubeconfig: ../config/admin.kubeconfig
        release_namespace: metallb-system
        chart_version: 0.12.1
        values: "{{ lookup('template', 'metallb/values.yaml') | from_yaml }}"
      tags: metallb

    - name: Create a service for external Emby media server
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: emby
            namespace: media
            labels:
              app: emby
          spec:
            ports:
              - protocol: TCP
                port: 8096
                targetPort: 8096
      tags: emby

    - name: Create endpoint for Emby service
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          apiVersion: v1
          kind: Endpoints
          metadata:
            name: emby
            namespace: media
            labels:
              app: emby
          subsets:
            - addresses:
              - ip: 192.168.100.2
              ports:
                - port: 8096
      tags: emby

    - name: Create ingress for Emby
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          apiVersion: v1
          kind: Ingress
          metadata:
            name: emby
            namespace: media
            labels:
              app: emby
            annotations:
              external-dns.alpha.kubernetes.io/hostname: emby.pco.pink
              cert-manager.io/cluster-issuer: letsencrypt
          spec:
            rules:
              - host: emby.pco.pink
                http:
                  paths:
                    - backend:
                        service:
                          name: emby
                          port:
                            number: 8096
                      path: /
                      pathType: Prefix
            tls:
              - hosts:
                - emby.pco.pink
                secretName: emby-tls-cert
      tags: emby

    - name: Create a service for nzbget on TrueNAS
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: nzbget
            namespace: media
            labels:
              app: nzbget
          spec:
            ports:
              - protocol: TCP
                port: 6789
                targetPort: 6789
      tags: nzbget

    - name: Create endpoint for nzbget service
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          apiVersion: v1
          kind: Endpoints
          metadata:
            name: nzbget
            namespace: media
            labels:
              app: nzbget
          subsets:
            - addresses:
              - ip: 192.168.1.129
              ports:
                - port: 6789
      tags: nzbget

    - name: Create ingress for nzbget
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          apiVersion: v1
          kind: Ingress
          metadata:
            name: nzbget
            namespace: media
            labels:
              app: nzbget
            annotations:
              external-dns.alpha.kubernetes.io/hostname: nzbget.pco.pink
              cert-manager.io/cluster-issuer: letsencrypt
          spec:
            rules:
              - host: nzbget.pco.pink
                http:
                  paths:
                    - backend:
                        service:
                          name: nzbget
                          port:
                            number: 6789
                      path: /
                      pathType: Prefix
            tls:
              - hosts:
                - nzbget.pco.pink
                secretName: nzbget-tls-cert
      tags: nzbget
