---
- hosts: all
  gather_facts: true

- hosts: localhost
  any_errors_fatal: true
  roles:
    - role: certs_and_config
      vars:
        certs_and_config_kube_api_public_ip: 192.168.10.1
        certs_and_config_cluster_name: rpi-cluster

- hosts: etcd
  any_errors_fatal: true
  become: true
  roles:
    - role: etcd_cluster
      vars:
        etcd_cluster_log_level: warn

- hosts: all
  any_errors_fatal: true
  become: true
  roles:
    - role: provision_control_plane
      vars:
        provision_control_plane_kube_api_public_ip: 192.168.10.1
        provision_control_plane_service_ip_range: 192.168.10.0/24
        provision_control_plane_pod_ip_range: 172.28.0.0/16
    - role: configure_ha
      vars:
        configure_ha_kube_api_public_ip: 192.168.10.1

- hosts: localhost
  any_errors_fatal: true
  tasks:
    - name: Create cluster role for kubelet auth
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRole
          metadata:
            annotations:
              rbac.authorization.kubernetes.io/autoupdate: "true"
            labels:
              kubernetes.io/bootstrapping: rbac-defaults
            name: system:kube-apiserver-to-kubelet
          rules:
            - apiGroups:
                - ""
              resources:
                - nodes/proxy
                - nodes/stats
                - nodes/log
                - nodes/spec
                - nodes/metrics
              verbs:
                - "*"

    - name: Create cluster role binding for kubelet auth
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: system:kube-apiserver
            namespace: ""
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: system:kube-apiserver-to-kubelet
          subjects:
            - apiGroup: rbac.authorization.k8s.io
              kind: User
              name: kubernetes

- hosts: all
  any_errors_fatal: true
  become: true
  roles:
    - role: provision_nodes
      vars:
        provision_nodes_pod_ip_range: 172.28.0.0/16
      tags:
        - nodes

- hosts: localhost
  any_errors_fatal: true
  become: false
  vars:
    metallb_loadbalancer_range: 192.168.50.0/24
  tasks:
    - name: Create a new k8s namespace for metallb
      kubernetes.core.k8s:
        state: present
        kubeconfig: ../config/admin.kubeconfig
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: metallb-system
            labels:
              app: metallb
      tags: metallb

    - name: Add MetalLB helm repo
      kubernetes.core.helm_repository:
        name: metallb
        repo_url: https://metallb.github.io/metallb
      tags: metallb

    - name: Deploy MetalLB version 0.12.1
      kubernetes.core.helm:
        name: metallb
        chart_ref: metallb/metallb
        kubeconfig: ../config/admin.kubeconfig
        release_namespace: metallb-system
        chart_version: 0.12.1
        values: "{{ lookup('template', 'metallb/values.yaml') | from_yaml }}"
      tags: metallb
