---
- hosts: all
  any_errors_fatal: true
  become: true
  tasks:
    - name: Fully upgrade the system
      ansible.builtin.apt:
        update_cache: true
        upgrade: full

    - name: Reboot the system after upgrade
      ansible.builtin.reboot:
