---
- hosts: all
  serial: 1
  gather_facts: true
  vars_prompt:
    - name: upgrade_provision_control_plane_k8s_version
      prompt: Enter the new version (e.g. v1.25.3)
      private: no
  roles:
  - role: upgrade_control_plane
