---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: media-shared
  name: media-shared
  namespace: media
spec:
  storageClassName: truenas-nfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
