apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: canozokur@gmail.com
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
    - dns01:
        cloudflare:
          email: canozokur@gmail.com
          apiTokenSecretRef:
            name: letsencrypt-cf-api-token
            key: api-token
